---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Device"
metadata:
  name: "pallab-test01" # Required
  labels:
    createdBy: pallab
    purpose: testing
spec:
  python: "3"
  rosDistro: "melodic" # Options: ["kinetic", "melodic" (default), "noetic"]
  virtual:
    enabled: True # Required
    product: "sootballs" # Required Options: ["sootballs", "flaptter", "oks"]
    arch: "amd64" # Options: ["amd64" (default), "arm64" ]
    os: "ubuntu" # Options: ["ubuntu" (default), "debian" ]
    codename: "focal" # Options: ["bionic", "focal" (default), "jammy", "bullseye"]
    highperf: False # Optional [True, False (default)]
  docker:
    enabled: True # Required
    rosbagMountPath: "/opt/rapyuta/volumes/rosbag"
