# Prints this help message
default:
    @just --list

RIO := "timeout 5 uv run rio"
DIR := justfile_directory()
VERBOSE := "false"

[private]
import-gpg-key:
    #!/bin/sh
    if ! gpg --list-secret-keys | grep E8CC457F956470ABA74B8DE072C7F68630BDEEA5 > /dev/null
    then
      gpg --import {{DIR}}/assets/gpg-key.asc > /dev/null
    fi

[private]
rbac-setup FILE:
    #!/bin/bash
    echo "Setting up RBAC bindings"
    set -euo pipefail
    while read line
    do
      echo "$line"
      {{RIO}} role bind $line
    done < <(cat {{DIR}}/{{FILE}} | grep -v "^#.*$" | grep .)

[private]
rbac-destroy FILE:
    #!/bin/bash
    echo "Destroy RBAC bindings"
    set -euo pipefail
    while read line
    do
      echo "$line"
      {{RIO}} role unbind $line
    done < <(cat {{DIR}}/{{FILE}} | grep -v "^#.*$" | grep .)

# Run Tests in a group
run GROUP:
    #!/bin/sh
    set -euo pipefail
    for recipe in $(just --dump --dump-format=json \
    | jq -r '.recipes | to_entries[] | select(.value.attributes[]? | type == "object" and has("group") and .group == "{{GROUP}}") | .key')
    do
      echo "Running - $recipe"
      if [ "{{VERBOSE}}" = "false" ]
      then
        just --explain "$recipe" > /dev/null
      else
        just --explain "$recipe"
      fi
      echo "Success - $recipe\n"
    done
    echo "All tests successful!"

# Apply/Delete single manifest with single worker
[group("negative")]
[group("apply")]
[group("all")]
test001:
    -{{RIO}} apply --workers 1 {{DIR}}/001/manifest.yaml
    -{{RIO}} delete --workers 1 {{DIR}}/001/manifest.yaml

# Apply/Delete multiple manifests with 3 workers
[group("negative")]
[group("apply")]
[group("all")]
test002:
    -{{RIO}} apply --workers 3 {{DIR}}/002/
    -{{RIO}} delete --workers 3 {{DIR}}/002/

# Apply/Delete chart with 3 workers
[group("negative")]
[group("apply")]
[group("all")]
test003:
    -{{RIO}} chart apply --workers 3 --values {{DIR}}/003/values.yaml gostproxy
    -{{RIO}} chart delete --workers 3 --values {{DIR}}/003/values.yaml gostproxy

# Value rendering
[group("positive")]
[group("apply")]
[group("all")]
test004: import-gpg-key
    {{RIO}} template {{DIR}}/004/manifests/without-value.yaml \
    | diff {{DIR}}/004/expected/without-value.yaml -

    {{RIO}} template \
      -v {{DIR}}/004/values.yaml \
      {{DIR}}/004/manifests/with-value.yaml \
      | diff {{DIR}}/004/expected/with-value.yaml -

    {{RIO}} template \
      -v {{DIR}}/004/values.yaml \
      -s {{DIR}}/004/secrets.yaml \
      {{DIR}}/004/manifests/with-value-secret.yaml \
      | diff {{DIR}}/004/expected/with-value-secret.yaml -

    {{RIO}} template \
      -v {{DIR}}/004/values.yaml \
      -v {{DIR}}/004/values-override.yaml \
      {{DIR}}/004/manifests/with-value.yaml \
      | diff {{DIR}}/004/expected/with-value-override.yaml -

    {{RIO}} template \
      -v {{DIR}}/004/values-rio.yaml \
      {{DIR}}/004/manifests/with-rio-namespace.yaml \
      | diff {{DIR}}/004/expected/with-rio-namespace.yaml -

# Dependency Graph
[group("positive")]
[group("apply")]
[group("all")]
test005:
    {{RIO}} graph --print-only {{DIR}}/005/manifests/network.yaml 2> /dev/null \
    | diff {{DIR}}/005/expected/network.txt -

    {{RIO}} graph --print-only {{DIR}}/005/manifests/package.yaml 2> /dev/null \
    | diff {{DIR}}/005/expected/package.txt -

    {{RIO}} graph --print-only {{DIR}}/005/manifests/deployment.yaml 2> /dev/null \
    | diff {{DIR}}/005/expected/deployment.txt -

    {{RIO}} graph --print-only {{DIR}}/005/manifests/usergroup.yaml 2> /dev/null \
    | diff {{DIR}}/005/expected/usergroup.txt -

    {{RIO}} graph --print-only {{DIR}}/005/manifests/rolebinding.yaml 2> /dev/null \
    | diff {{DIR}}/005/expected/rolebinding.txt -

[group("negative")]
[group("rbac")]
[group("all")]
test006: (rbac-setup "006/rbac-setup")
    just --explain rbac-destroy "006/rbac-setup" > /dev/null
