apiVersion: apiextensions.rapyuta.io/v1
kind: Deployment
metadata:
  name: cvat_db
  depends:
    kind: package
    nameOrGUID: cvat_db_redis
    version: "v1.0.2"
  labels:
    app: cvat
spec:
  runtime: cloud
  envArgs:
    - name: PGDATA
      value: "/var/lib/postgresql/data/pgdata"
    - name: POSTGRES_DB
      value: "cvat"
    - name: POSTGRES_USER
      value: root
    - name: POSTGRES_HOST_AUTH_METHOD
      value: "trust"
  volumes:
    - execName: postgres
      mountPath: "/var/lib/postgresql/data"
      depends:
        kind: disk
        nameOrGUID: "cvat_data_128gb"
  staticRoutes:
    - name: CVAT_UI
      depends:
        kind: staticroute
        nameOrGUID: cvat-prod
---
apiVersion: apiextensions.rapyuta.io/v1
kind: Deployment
metadata:
  name: cvat_prod
  depends:
    kind: package
    nameOrGUID: cvat_custom
    version: "v1.3.0"
  labels:
    app: cvat
spec:
  depends:
    - kind: deployment
      nameOrGUID: cvat_db
  runtime: cloud
  envArgs:
    - name: DJANGO_MODWSGI_EXTRA_ARGS
      value: " "
    - name: ALLOWED_HOSTS
      value: "*"
  volumes:
    - execName: cvat_server
      mountPath: "/home/django/user_data"
      depends:
        kind: disk
        nameOrGUID: "cvat_data_128gb"
  staticRoutes:
    - name: CVAT_UI
      depends:
        kind: staticroute
        nameOrGUID: cvat-prod