apiVersion: apiextensions.rapyuta.io/v1
kind: Deployment
metadata:
  name: pgAdmin
  depends:
    kind: package
    nameOrGUID: pgAdmin
    version: "v1.0.1"
  labels:
    app: cvat
spec:
  depends:
    - kind: deployment
      nameOrGUID: cvat_db
  runtime: cloud
  envArgs:
    - name: PGADMIN_DEFAULT_PASSWORD
      value: "pgadmin"
    - name: PGADMIN_DEFAULT_EMAIL
      value: "pgadmin@rapyuta-robotics.com"
  volumes:
    - execName: cvat_server
      mountPath: "/home/django/user_data"
      depends:
        kind: disk
        nameOrGUID: "cvat_data_128gb"
  staticRoutes:
    - name: endpoint
      depends:
        kind: staticroute
        nameOrGUID: cvat-prod