---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "git-ssh"
spec:
  type: Git
  git:
    authMethod: SSH Auth
    privateKey: |
      private-key
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "git-basic"
spec:
  type: Git
  git:
    authMethod: HTTP/S Basic Auth
    username: user
    password: password
    # caCert:
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "git-token"
spec:
  type: Git
  git:
    authMethod: HTTP/S Token Auth
    token: token
    # caCert:
