apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "docker-secret"
spec:
  type: Docker
  username: user
  password: password
  registry: index.docker.io
  email: user@example.net
