apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "docker-secret"
spec:
  type: Docker
  docker:
    username: user
    password: password
    email: user@example.net
    # registry: https://index.docker.io/v1/
