apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "sootballs"
  guid: secret-vebkjobybhhwmyiwkwvndagu
spec:
  type: Docker
  docker:
    username: shaishavrapyuta
    password: asdfg123$
    email: shaishavrapyuta
    # registry: https://index.docker.io/v1/
