---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: "Sootballs SUI2"
  version: "1.0.0"
  labels:
    app: sootballs
spec:
  runtime: "cloud"
  ros:
    enabled: True
    version: "melodic"
    rosEndpoints:
      - name: "/cmd_global_charge"
        type: "topic"
        qos: "hi"
      - name: "/cmd_global_in"
        type: "topic"
        qos: "hi"
      - name: "/cmd_move_to"
        type: "topic"
        qos: "hi"
      - name: "/dispatcher/active_tote_unload_request"
        type: "topic"
        qos: "low"
      - name: "/dispatcher/control_request"
        type: "topic"
        qos: "low"
      - name: "/dispatcher/modify_order_request"
        type: "topic"
        qos: "low"
      - name: "/dispatcher/productivity_configs_request"
        type: "topic"
        qos: "low"
      - name: "/edge/emergency_released_request"
        type: "topic"
        qos: "low"
      - name: "/manual_order_recovery"
        type: "topic"
        qos: "hi"
      - name: "/reservation_request"
        type: "topic"
        qos: "hi"
  cloud:
    replicas: 1
  executables:
    - name: "systemui"
      type: docker
      docker:
        image: "rrdockerhub/sootballs:1.14.0-rc4"
        pullSecret:
          depends:  
            kind: secret
            nameOrGUID: sootballs
      command: "roslaunch sootballs_applications_edge remote_ui.launch"
      limits:
        cpu: 2
        memory: 8192
      
  environmentVars:
    - name: "IMS_AUTH_USERNAME"
      description: "Username to authenticate to IMS"
      defaultValue: "root"
    - name: "IMS_AUTH_PASSWORD"
      description: "Password to authenticate to IMS"
      defaultValue: "airborne_rr"
    - name: "SENTRY_DSN"
      description: "Password to authenticate to IMS"
      defaultValue: "https://a83904fb2f394a768557eaea8ec39db4:7d8a02b629994bf884534917dfb08511@sentry.svc.rapyuta.io/18"
    - name: "SOOTBALLS_MAP"
      defaultValue: "rrkibstg"
    - name: "SYSTEM_UI_REMOTE_MODE"
      defaultValue: "true"
    - name: "WS_EXTERNAL_PORT"
      defaultValue: "80"
    - name: "DOCKER_STDOUT"
      defaultValue: "true"
  endpoints:
    - name: "SYSTEM_UI"
      type: external-https
      port: 443
      targetPort: 7099
    - name: "SYSTEM_UI_ROSBRIDGE_URL"
      type: external-https
      port: 443
      targetPort: 9092
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: "Sootballs Edge2"
  version: "1.0.0"
  labels:
    app: sootballs
spec:
  runtime: "device"
  device:
    arch: amd64
    restart: always
  ros:
    enabled: True
    version: "melodic"
    rosEndpoints:
      - name: "/dispatcher/control_response"
        type: "topic"
        qos: "low"
      - name: "/dispatcher/modify_order_response"
        type: "topic"
        qos: "low"
      - name: "/dispatcher/productivity_configs_response"
        type: "topic"
        qos: "low"
      - name: "/dispatcher/active_tote_unload_response"
        type: "topic"
        qos: "low"
      - name: "/edge/emergency_released_response"
        type: "topic"
        qos: "low"
      - name: "/robot_reservation"
        type: "topic"
        qos: "low"
      - name: "/sui/status"
        type: "topic"
        qos: "low"
      - name: "/sui/overview"
        type: "topic"
        qos: "low"
      - name: "/sui/main"
        type: "topic"
        qos: "low"
  executables:
    - name: "systemui"
      type: docker
      docker:
        image: "rrdockerhub/sootballs:1.14.0-rc4"
        pullSecret:
          depends:
            kind: secret
            nameOrGUID: sootballs
      command: "roslaunch sootballs_applications_edge default.launch --wait"
      
  environmentVars:
    - name: "IMS_AUTH_USERNAME"
      description: "Username to authenticate to IMS"
      defaultValue: "root"
    - name: "IMS_AUTH_PASSWORD"
      description: "Password to authenticate to IMS"
      defaultValue: "airborne_rr"
    - name: "SENTRY_DSN"
      description: "Password to authenticate to IMS"
      defaultValue: "https://a83904fb2f394a768557eaea8ec39db4:7d8a02b629994bf884534917dfb08511@sentry.svc.rapyuta.io/18"
    - name: "DOCKER_STDOUT"
      defaultValue: "true"
    - name: "DISABLE_MULTICAST"
      defaultValue: "false"
    - name: "ROS_DOMAIN_ID"
      defaultValue: "10"
    - name: "USE_PARAMS_IO"
      defaultValue: "true"
    - name: "EDGE_ALARM_MONITOR"
      defaultValue: "true"
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: "Sootballs Robot2"
  version: "1.0.0"
  labels:
    app: sootballs
spec:
  runtime: "device"
  device:
    arch: amd64
    restart: always
  ros:
    enabled: True
    version: "melodic"
  executables:
    - name: "systemui"
      type: docker
      docker:
        image: "rrdockerhub/sootballs:1.14.0-rc4"
        pullSecret:
          depends:
            kind: secret
            nameOrGUID: sootballs
      command: "roslaunch sootballs_applications_edge default.launch --wait"
      
  environmentVars:
    - name: "IMS_AUTH_USERNAME"
      description: "Username to authenticate to IMS"
      defaultValue: "root"
    - name: "IMS_AUTH_PASSWORD"
      description: "Password to authenticate to IMS"
      defaultValue: "airborne_rr"
    - name: "SENTRY_DSN"
      description: "Password to authenticate to IMS"
      defaultValue: "https://a83904fb2f394a768557eaea8ec39db4:7d8a02b629994bf884534917dfb08511@sentry.svc.rapyuta.io/18"
    - name: "DOCKER_STDOUT"
      defaultValue: "true"
    - name: "DISABLE_MULTICAST"
      defaultValue: "false"
    - name: "ROS_DOMAIN_ID"
      defaultValue: "10"
    - name: "USE_PARAMS_IO"
      defaultValue: "true"