apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: sootballs_ims
  version: v1.14.0-rc4-6
  description: Sootballs IMS Package
  labels:
    app: ims
spec:
  runtime: cloud
  cloud:
    replicas: 1
  executables:
    - type: docker
      name: Django
      docker:
        image: rrdockerhub/sootballs_ims:1.14.0-rc4
        pullSecret:
          depends:
            kind: secret
            nameOrGUID: sootballs
      limits:
        cpu: 0.5
        memory: 2048
  environmentVars:
    - name: SECRET_KEY
    - name: AUTH_ENABLED
      default: "False"
    - name: TIMEZONE
      default: "Asia/Tokyo"
    - name: CONTAINER_NAME
      default: "warehouse"
    - name: DAYS_BEFORE_ARCHIVE
      default: "15"
    - name: DEPLOY_ON_CLOUD
      default: "False"
    - name: SODTIME
      default: "09:00"
    - name: EODTIME
      default: "19:00"
    - name: AWS_STORAGE_BUCKET_NAME
      default: "kiba-robots"
    - name: IMS_DB
      default: ims_db
    - name: CELERY_BROKER_URL
    - name: CELERY_RESULT_BACKEND
    
  endpoints:
    - name: IMS_URL
      type: external-https
      port: 443
      targetPort: 8002
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: sootballs_db
  version: v1.0.11
  description: Sootballs DB package
  labels:
    app: ims
spec:
  runtime: cloud
  cloud:
    replicas: 1
  executables:
    - type: docker
      name: redis
      docker:
        image: redis:4.0-alpine
      limits:
        cpu: 0.5
        memory: 2048
    - type: docker
      name: postgres
      docker:
        image: postgis/postgis:9.6-3.2
      limits:
        cpu: 1
        memory: 4096
  environmentVars:
    - name: POSTGRES_MULTIPLE_DATABASES
      default: ims_db,wcs_db
    - name: PGDATA
      default: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_HOST_AUTH_METHOD
      default: trust
    - name: POSTGRES_USER
      default: postgres
      exposed: true
      exposedName: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      default: password
      exposed: true
      exposedName: POSTGRES_PASSWORD
  endpoints:
    - name: POSTGRES
      type: internal-tcp
      port: 5432
      targetPort: 5432
    - name: REDIS
      type: internal-tcp
      port: 6379
      targetPort: 6379
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: MinIO File Server
  version: v1.0.11
  description: Sootballs File Server package
  labels:
    app: ims
spec:
  runtime: cloud
  cloud:
    replicas: 1
  executables:
    - type: docker
      name: minio_executable
      docker:
        image: rrdockerhub/minio-server
      limits:
        cpu: 1
        memory: 4096
  environmentVars:
    - name: MINIO_ACCESS_KEY
    - name: MINIO_SECRET_KEY
  endpoints:
    - name: MINIO
      type: external-https
      port: 443
      targetPort: 9000
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: sootballs_wcs
  version: v1.14.0-rc4-2
  description: Sootballs WCS package 
  labels:
    app: wcs
spec:
  runtime: cloud
  cloud:
    replicas: 1
  executables:
    - type: docker
      name: django
      command: /code/docker/entrypoint.sh
      docker:
        image: rrdockerhub/sootballs_wcs:1.14.0-rc4
        pullSecret:
          depends:
            kind: secret
            nameOrGUID: sootballs
      limits:
        cpu: 1
        memory: 4096
  environmentVars:
    - name: TIMEZONE
      default: Asia/Tokyo
    - name: WCS_DB
      default: wcs_db
    - name: CELERY_BROKER_URL
    - name: CELERY_RESULT_BACKEND
    - name: LOCAL_PRINT_SERVER_URL
    - name: SECRET_KEY
  endpoints:
    - name: WCS_URL
      type: external-https
      port: 443
      targetPort: 8003