---
#sootballs_db
apiVersion: apiextensions.rapyuta.io/v1
kind: Deployment
metadata:
  name: sootballs_db
  depends:
    kind: package
    nameOrGUID: sootballs_db
    version: "v1.0.11"
  labels: 
    app: ims
spec:
  runtime: cloud
  envArgs:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    - name: POSTGRES_MULTIPLE_DATABASES
      value: ims_db,wcs_db
    - name: POSTGRES_PASSWORD
      value: sootballs
    - name: POSTGRES_USER
      value: postgres
  volumes:
    - execName: postgres
      mountPath: "/var/lib/postgresql/data/pgdata"
      subPath: "pgdata"
      depends:
        kind: disk
        nameOrGUID: "postgres-pvc"
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: sootballs_db
  version: v1.0.11
  description: Sootballs DB package
  labels:
    app: ims
spec:
  runtime: cloud
  cloud:
    replicas: 1
  executables:
    - type: docker
      name: redis
      docker:
        image: redis:4.0-alpine
      limits:
        cpu: 0.5
        memory: 2048
    - type: docker
      name: postgres
      docker:
        image: postgis/postgis:9.6-3.2
      limits:
        cpu: 1
        memory: 4096
  environmentVars:
    - name: POSTGRES_MULTIPLE_DATABASES
      default: ims_db,wcs_db
    - name: PGDATA
      default: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_HOST_AUTH_METHOD
      default: trust
    - name: POSTGRES_USER
      default: postgres
      exposed: true
      exposedName: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      default: password
      exposed: true
      exposedName: POSTGRES_PASSWORD
  endpoints:
    - name: POSTGRES
      type: internal-tcp
      port: 5432
      targetPort: 5432
    - name: REDIS
      type: internal-tcp
      port: 6379
      targetPort: 6379
