---
apiVersion: apiextensions.rapyuta.io/v1
kind: Deployment
metadata:
  name: deployment-nonros-device
  depends:
    kind: package
    nameOrGUID: "package-nonros-device"
    version: "v1.0.0"
  labels:
    app: test
spec:
  runtime: device # Options: [device, cloud]
  device:
    depends:
      kind: device
      nameOrGUID: device-docker
  restart: always # Options: [always, onfailure, never]
  features:
    params:
      enabled: true
      trees:
        - config01
        - config02
      blockUntilSynced: true # Optional [true, false]. Default is false.
  envArgs:
    - name: TEST_KEY
      value: test_value
  volumes:
    - execName: exec-docker
      mountPath: "/tmp" # Path on container
      subPath: "/tmp" # Path on device
      uid: 1000 # Optional userid for subpath
      gid: 1000 # Optional groupid for subpath
      perm: 755 # Optional permissions for subpath