---
apiVersion: apiextensions.rapyuta.io/v1
kind: Deployment
metadata:
  name: deployment-ros-cloud
  depends:
    kind: package
    nameOrGUID: "package-ros-cloud"
    version: "v1.0.0"
  region: jp
  labels:
    app: test
spec:
  runtime: cloud # Options: [device, cloud]
  depends:
    - kind: deployment
      nameOrGUID: "dep-guid"
      wait: false # Options: [true, false] Wait until dependency is ready
  envArgs:
    - name: TEST_KEY
      value: test_value
  volumes:
    - execName: exec-docker
      mountPath: "/tmp" # Path on container
      subPath: "/tmp" # Path on volume
      depends:
        kind: disk
        nameOrGUID: "disk"
  staticRoutes:
    - name: NAME
      depends:
        kind: staticroute
        nameOrGUID: "staticroute"
  rosNetworks:
    - depends:
        kind: network
        nameOrGUID: "network-native-cloud"
    - depends:
        kind: network
        nameOrGUID: "network-routed-cloud"
  managedServices:
    - depends:
        kind: managedservice
        nameOrGUID: "managedservice"
  features:
    vpn:
      enabled: true
    params:
      enabled: true
      trees:
        - config01
        - config02