apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Disk"
metadata:
  name: "disk"
  project: "project-guid"
  labels:
    app: test
spec:
  runtime: cloud
  capacity: 4 #  Options: [4, 8, 16, 32, 64, 128, 256, 512]
