apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Network"
metadata:
  name: "network-native-device"
  labels:
    app: test
spec:
  type: "native" # Required, Options: [routed, native]
  rosDistro: "melodic" # Required, Options: [kinetic, melodic, noetic]
  runtime: "device" # Required, Options: [cloud, device]
  depends: # Required
    nameOrGuid: device-name
  networkInterface: "eth0" # Required
  restartPolicy: "always" # Options: [always, never, onFailure]
