apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Package"
metadata:
  name: "package-nonros-device" # Required
  version: "v1.0.0" # Required
  description: "A RIO non ROS device package"
  project: "project-guid"
  labels:
    app: test
spec:
  runtime: device # Options: [device, cloud(default)]
  device:
    arch: amd64 # Options: [arm32v7, arm64v8, amd64]
    restart: always # Options: [always, never, onfailure]
  executables: # Required
    - name: "exec-build"
      type: build # Options: [docker (default), build, preInstalled]
      command: "roslaunch talker talker.launch"
      runAsBash: True
      limits: # Optional
        cpu: 0.025 # Unit: Core (Optional)
        memory: 128 # Unit: MB (Optional)
      livenessProbe: # Optional
        exec:
          command:
            - "shell-cmd"
        initialDelaySeconds: 5  # Number of seconds after the container has started before liveness probes are initiated.
        periodSeconds: 10 # How often (in seconds) to perform the probe.
        failureThreshold: 1 # Minimum consecutive failures for the probe to be considered failed after having succeeded.
        successThreshold: 3 # Minimum consecutive successes for the probe to be considered successful after having failed.
        timeoutSeconds: 1 # Number of seconds after which the probe times out.
      build:
        depends:
          kind: build
          nameOrGUID: "build"
    - name: "exec-docker"
      type: docker # Options: [docker (default), build, preInstalled]
      command: "roslaunch talker talker.launch"
      runAsBash: True
      limits: # Optional
        cpu: 0.025 # Unit: Core (Optional)
        memory: 128 # Unit: MB (Optional)
      livenessProbe:
        httpGet:
          path: "/"
          port: 90
        initialDelaySeconds: 5  # Number of seconds after the container has started before liveness probes are initiated.
        periodSeconds: 10 # How often (in seconds) to perform the probe.
        failureThreshold: 1 # Minimum consecutive failures for the probe to be considered failed after having succeeded.
        successThreshold: 3 # Minimum consecutive successes for the probe to be considered successful after having failed.
        timeoutSeconds: 1 # Number of seconds after which the probe times out.

      docker:
        image: "busybox:latest"
        imagePullPolicy: "Always" # Always, Never, IfNotPresent(default)
        pullSecret:
          depends:
            kind: secret
            nameOrGUID: "secret-docker"
    - name: "exec-preInstalled"
      type: preInstalled # Options: [docker (default), build, preInstalled]
      command: "roslaunch talker talker.launch"
  environmentArgs:
    - name: "key1" # Required
      default: "key1-value"
      description: "A environment variable"
      exposed: False
    - name: "key2" # Required
      default: "key2-value"
      description: "A environment variable"
      exposed: True
      exposedName: "EXPOSED_KEY2"