---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "secret-docker"
  labels:
    app: test
spec:
  type: Docker
  docker:
    username: user # Required
    password: password # Required
    email: user@example.net # Required
    registry: https://index.docker.io/v1/
---
# Below examples are Deprecated. Git secret support will be removed.
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "git-ssh"
spec:
  type: Git
  git:
    authMethod: SSH Auth
    privateKey: |
      private-key
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "git-basic"
spec:
  type: Git
  git:
    authMethod: HTTP/S Basic Auth
    username: user
    password: password
    caCert: ""
---
apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "git-token"
spec:
  type: Git
  git:
    authMethod: HTTP/S Token Auth
    token: token
    caCert: ""