---
apiVersion: api.rapyuta.io/v2
kind: UserGroup
metadata:
  name: usergroup_name
  labels:
    key: value
spec:
  description: This is a sample user group description
  members:
  - subject:
      kind: User
      name: qa.rapyuta+e2e@gmail.com
    roles: [group_admin]
  - subject:
      kind: ServiceAccount
      name: sa-paramsync
    roles: [group_viewer]
  roles:
  - domain:
      kind: Project
      name: site-1
    roles: [project_admin]
  - domain:
      kind: Project
      name: site-2
    roles: [project_viewer]
