name: Check Commit Hygiene 💬

on: [ pull_request, pull_request_review, pull_request_target]

jobs:
  verify:
    name: Conventional Commits
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - uses: webiny/action-conventional-commits@v1.1.0
      name: Check if commit messages are compliant
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}