name: 💬 Check Commit Hygiene

on:
  pull_request:
    branches:
      - main
      - devel

jobs:
  verify:
    name: Conventional Commits
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - uses: rapyuta-robotics/action-conventional-commits@v1.1.1
      name: Check if commit messages are compliant
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
