name: 📝 Github Pages for Documentation
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Dependencies
        run: uv sync --dev

      - name: Build Documentation
        run: |
          uv run python -m sphinx -M html docs/source docs/output
          cp scripts/install.sh docs/output/html/install.sh

      - name: Deploy gh-pages
        if: github.repository == 'rapyuta-robotics/rapyuta-io-cli' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/output/html
          cname: cli.rapyuta.io
          force_orphan: true
