name: ✅ Quality Checks
on: [ push ]

permissions:
  contents: read

jobs:
  code-quality-checks:
    runs-on: aks-spot-4cpu
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ruff check
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"

      - name: Run ruff format --check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

  unit-tests:
    runs-on: aks-spot-4cpu
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Run unit tests
        run: uv run pytest tests/unit/ -v --tb=short