name: 🎉 Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run semantic-release
        run: |
          npm install --save-dev semantic-release@24.2.3
          npm install @semantic-release/git -D
          npm install @semantic-release/changelog -D
          npm install @semantic-release/exec -D
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MINIO_URL: ${{ secrets.MINIO_URL }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET: ${{ secrets.MINIO_SECRET }}
