name: Upload AppImage
on:
  push:
    branches:
    - main
    - devel
  pull_request:

jobs:
  upload-appimage:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create AppImage
        run: ./scripts/build-rio-appimage.sh
        shell: bash
        env:
          MINIO_URL: ${{ secrets.MINIO_URL }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET: ${{ secrets.MINIO_SECRET }}

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v3
        with:
          name: appimages
          path: ${{ github.workspace }}/scripts/rio*.AppImage
          if-no-files-found: error
          retention-days: 15

      - name: Artifact Comment on PR
        if: github.event_name == 'pull_request'
        run: |
          gh pr comment $PR_NUMBER -b  "
          **🤖 Pull Request [Artifacts](https://github.com/rapyuta-robotics/rapyuta-io-cli/actions/runs/"$RUN_ID") (#"$RUN_ID") 🎉**
          "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          PR_NUMBER: ${{ github.event.number }}